# Generated by Django 5.0.6 on 2024-07-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('pickup', 'Pickup Truck'), ('semi', 'Semi-Truck'), ('box', 'Box Truck'), ('dump', 'Dump Truck'), ('flatbed', 'Flatbed Truck'), ('tanker', 'Tanker Truck')], max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'trucks',
            },
        ),
    ]
