# Generated by Django 5.0.6 on 2024-07-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_alter_trucks_options_and_more'),
        ('users', '0011_buyer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucks',
            name='purchasedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_trucks', to='users.buyer'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='users.buyer'),
        ),
    ]
