# Generated by Django 4.2.14 on 2024-07-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_buyer_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='state',
        ),
    ]
