# Generated by Django 4.2.14 on 2024-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_buyer_gender_remove_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='lastname',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
