# Generated by Django 4.2.14 on 2024-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_buyer_gender_remove_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='lastname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyer',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
