# Generated by Django 4.2.14 on 2024-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_buyer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
