# Generated by Django 5.0.6 on 2024-07-21 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_options'),
        ('users', '0008_remove_buyer_gender_remove_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='bikes/'),
        ),
    ]
