# Generated by Django 5.0.6 on 2024-07-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_purchasedby'),
        ('users', '0011_buyer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cars.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyer')),
            ],
            options={
                'unique_together': {('car', 'user')},
            },
        ),
    ]
