# Generated by Django 5.0.6 on 2024-06-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
