# Generated by Django 5.0.6 on 2024-07-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_rating_date_created_alter_rating_rating'),
        ('bikes', '0005_alter_bikes_image'),
        ('cars', '0002_alter_cars_options'),
        ('trucks', '0002_alter_trucks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.bikes'),
        ),
        migrations.AddField(
            model_name='rating',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.trucks'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
