# Generated by Django 5.0.6 on 2024-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('modelType', models.CharField(choices=[('road', 'Road Bike'), ('mountain', 'Mountain Bike'), ('hybrid', 'Hybrid Bike'), ('cruiser', 'Cruiser Bike')], max_length=100)),
                ('manufacturingYear', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('isNew', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
