# Generated by Django 5.0.6 on 2024-07-07 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
