# Generated by Django 5.0.6 on 2024-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_alter_bikes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(upload_to='bikes/'),
        ),
    ]
