# Generated by Django 5.0.6 on 2024-07-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
